FROM arm64v8/node:lts-alpine 
MAINTAINER fine<dlgmltjr0925@gmail.com>

EXPOSE 3000

# Create Work directory
RUN mkdir -p /docker-registry-ui

# Change Work directory 
WORKDIR /docker-registry-ui

# Copy package info
COPY . .

ENTRYPOINT ["yarn"];
ENTRYPOINT ["yarn", "build"];

# Run Server
CMD ["yarn", "start"];
